project:
  name: nanopore-structure-featurizer
  version: 0.1.0

input:
  pdb_id: T274L_N226Q_S228K_MD_frame1
  nanopore_id: aerolysin_T274L_N226Q_S228K_MD_frame1
  structure_file: data/raw/T274L_N226Q_S228K_MD/LQK_final.pdb
  file_format: pdb
  assembly_type: md_snapshot
  structure_source_type: molecular_dynamics_snapshot
  template_pdb_id: 5JZT
  modeling_method: MD
  mutation_list:
    - T274L
    - N226Q
    - S228K

structure:
  use_model_index: 0
  use_standard_residues_only: true
  use_ca_only: true

pore:
  axis_mode: z_axis
  center_mode: xy_mean
  inner_radius_threshold: 20.0

output:
  interim_dir: data/interim
  processed_dir: data/processed
  chain_summary_dir: data/processed/chain_summary
  residue_feature_dir: data/processed/residue_features
  inner_residue_dir: data/processed/inner_residues
  nanopore_feature_dir: data/processed/nanopore_features

save:
  chain_summary: true
  residue_features: true
  inner_candidate_residues: true
  nanopore_features: true

foldx:
  executable: tools/foldx/foldx_1_20270131.exe
  work_dir: data/foldx
  input_dir: data/foldx/input
  repaired_dir: data/foldx/repaired
  mutant_dir: data/foldx/mutants
  modeled_dir: data/modeled
